version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    command: [
      "--log-level=debug",
      "--collector.zipkin.http-port=9411",
      "--sampling.strategies-file=/etc/jaeger/sampling_strategies.json"
    ]
    volumes:
      - ./sampling_strategies.json:/etc/jaeger/sampling_strategies.json
